name = "adr-fr-api"
main = "src/index.ts"
compatibility_date = "2024-11-01"

[vars]
IMPORT_TOKEN = "qwerty123"
BUILD_TAG = "wallboard-v11-hybrid"

[[d1_databases]]
binding = "DB"
database_name = "adr_fr"
database_id = "eedd9a67-410c-4bc9-b428-5bf7c3f12773"

routes = [
  { pattern = "s.adr-fr.org/*", zone_name = "adr-fr.org" }
]
