name = "adr-fr-api"
main = "workers/api/index.ts"
compatibility_date = "2024-10-01"

[assets]
directory = "site"

[[d1_databases]]
binding = "DB"
database_name = "adr_fr"
database_id = "REPLACE_WITH_YOUR_D1_UUID"
